### ISSUE TITLE
 "leds_off: true" pyrpl configuration parameter, output to input crosstalk

### ISSUE THREAD

**Issue by tt-aqt** [lneuhaus/pyrpl#451]
Does this work?  From pyrpl.redpitaya default parameters

`
leds_off=True,  # turn off all GPIO lets at startup (improves analog performance)`

https://pyrpl.readthedocs.io/en/latest/_modules/pyrpl/redpitaya.html

it seems you are supposed to be able to turn off the LEDs?  I have entered this in my configuration file as well

```
redpitaya:
  autostart: true
  delay: 0.05
  frequency_correction: 1.0
  gui: true
  hostname: 192.168.1.201
  leds_off: true
  monitor_server_name: pyrpl_server
  password: root
  port: 2222
  recompileserver: false
  reloadfpga: true
  reloadserver: true
  serverbinfilename: fpga.bin
  serverdirname: //opt//pyrpl//
  silence_env: false
  sshport: 22
  timeout: 1
  user: root
```

Are "GPIO LEDS" different from the blue, green, red, orange LEDS?

https://redpitaya.readthedocs.io/en/latest/developerGuide/125-14/leds.html

Blue, green, and blinking red are always on for me.  The others on the board alongside them stay off.  Maybe those are the "GPIO LEDs?"  Is this the expected behavior?

I am trying to debug a nasty input/output crosstalk issue I am seeing with a hardware engineer at Red Pitaya.  Doesn't seem likely that this is the problem.  He brought up the known issue of LEDs and I am just trying to rule this out.

For some Red Pitayas I see a spike up to 50mV on the input signal when the output (green) sweeps through a "problematic" level.   The output must be increasing and the input (red) must be decreasing.  The faster the input is decreasing, the larger the spike on the input is.  Seems like some kind of bit flip issue?  The position of the spike is determined by the output level and slope only.

![grafik](https://user-images.githubusercontent.com/60933247/123290952-f7979980-d511-11eb-81d8-6f8ebf0f2632.png)
